# Generated by Django 4.0.3 on 2022-04-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='boom', max_length=500),
            preserve_default=False,
        ),
    ]
