# Generated by Django 4.0.4 on 2022-05-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(default='OPEN', max_length=10),
        ),
    ]
