# Generated by Django 4.0.3 on 2022-04-19 14:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
