# Generated by Django 4.0.4 on 2022-05-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_event_isdeleted_alter_event_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizersofevent',
            name='event',
        ),
        migrations.AddField(
            model_name='organizersofevent',
            name='event',
            field=models.ManyToManyField(blank=True, null=True, to='api.event'),
        ),
        migrations.RemoveField(
            model_name='organizersofevent',
            name='organizer',
        ),
        migrations.AddField(
            model_name='organizersofevent',
            name='organizer',
            field=models.ManyToManyField(blank=True, null=True, to='api.organizer'),
        ),
    ]
