# Generated by Django 4.0.3 on 2022-04-21 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_organizer_alter_event_options_event_organizers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
        migrations.AlterModelOptions(
            name='organizer',
            options={},
        ),
    ]
