# Generated by Django 4.0.4 on 2022-05-04 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_organizersofevent_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizersofevent',
            name='event',
        ),
        migrations.AddField(
            model_name='organizersofevent',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.event'),
        ),
        migrations.RemoveField(
            model_name='organizersofevent',
            name='organizer',
        ),
        migrations.AddField(
            model_name='organizersofevent',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.organizer'),
        ),
    ]
