# Generated by Django 4.0.4 on 2022-05-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_organizersofevent_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventOrganizers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ManyToManyField(blank=True, to='api.event')),
                ('organizer', models.ManyToManyField(blank=True, to='api.organizer')),
            ],
        ),
    ]
