# Generated by Django 4.0.3 on 2022-04-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_event_options_alter_organizer_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratedate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_gte', models.DateField()),
                ('date_lte', models.DateField()),
            ],
        ),
    ]
