# Generated by Django 4.0.4 on 2022-05-06 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_eventorganizers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventOrganizers',
        ),
    ]
