# Generated by Django 4.0.3 on 2022-04-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_ratedate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ratedate',
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10),
        ),
    ]
