# Generated by Django 4.0.4 on 2022-04-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_event_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='code',
            field=models.CharField(max_length=5),
        ),
    ]
