# Generated by Django 4.0.4 on 2022-04-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_event_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='org_id',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
